@baseUrl = http://localhost:8080/api
//Lista todas as categorias
get {{baseUrl}}/categories

###
get {{baseUrl}}/categories/1795089d-bbea-459d-8184-eb5f5d0dd013

###

//Cria um novo produto
post {{baseUrl}}/categories
Content-Type: application/json

{
  "name": "Category 1",
  "description": "Category 1 description"
}




###

//Atualiza um produto existente
PUT {{baseUrl}}/products/1795089d-bbea-459d-8184-eb5f5d0dd013
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Other description of Product 1",
  "price": 10.0,
  "quantity": 100
}




###
// Deleta um produto existente (esperado: 204 No Content)
DELETE {{baseUrl}}/products/1795089d-bbea-459d-8184-eb5f5d0dd013

###
// Retorna um produto existente (esperado: 404 Not Found)
DELETE {{baseUrl}}/products/5
